### ISSUE TITLE
yu7t8y12222sss2333ss

### ISSUE THREAD

**Issue by Tomnmy** [plainheart/issue-pr-bot-test#33]
This issue is in English.
generated by echarts-issue-helper
Steps to Reproduce
1

**Comment by plainheart** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/css/example-bundle.css?_v_=1023d89d52
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/js/example-bundle.js?_v_=1d8f5a874b

**Comment by plainheart** [comment]
@jsdelivrbot purge https://fastly.jsdelivr.net/gh/apache/echarts-website@asf-site/examples/js/example-bundle.js?_v_=34eb1bf85f
